/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeYiTraceDB {
  constructor(dataDir: string)
  ingestJson(eventsJson: string, tenantId?: string | undefined | null): string
  ingestOtlpJson(otlpJson: string, tenantId?: string | undefined | null): string
  searchJson(queryJson: string, tenantId?: string | undefined | null): string
  tracesJson(tenantId?: string | undefined | null): string
  sessionsJson(cursor?: number | undefined | null, limit?: number | undefined | null, filter?: string | undefined | null, attrsJson?: string | undefined | null, tenantId?: string | undefined | null): string
  traceJson(traceId: string, tenantId?: string | undefined | null): string
  spanJson(traceId: string, spanId: string, tenantId?: string | undefined | null): string
  flush(): void
  close(): void
}
export type NativeYiTraceDb = NativeYiTraceDB
